/** AUDIT_ENGINE §4：穩定的機器可讀理由目錄。新增項目必須附測試。 */
export const REASONING_CODES = [
  'AMT_EXACT',
  'AMT_TENFOLD',
  'AMT_OFFSET_10',
  'AMT_OFFSET_100',
  'AMT_OFFSET_1000',
  'AMT_SIGN_FLIPPED',
  'FX_RATE_WITHIN_TOL',
  'FX_ROUNDING',
  'DATE_SAME',
  'DATE_WITHIN_TOL',
  'POSTING_LAG_TYPICAL',
  'DATE_FAR',
  'MERCHANT_ALIAS',
  'MERCHANT_NORMALIZED_EQ',
  'MERCHANT_FUZZY',
  'MERCHANT_MISMATCH',
  'CARD_LAST4_MATCH',
  'CARD_LAST4_MISMATCH',
  'INSTALLMENT_SEQ_MATCH',
  'INSTALLMENT_MISMATCH',
  'REFUND_PAIR',
  'DUPLICATE_SUSPECT',
  'USER_HISTORY_MATCH',
  'BALANCES_STATEMENT',
] as const;

export type ReasoningCode = (typeof REASONING_CODES)[number];
